[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrains Mono NL"
style = "Medium"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[window]
startup_mode = "Fullscreen"
