[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrains Mono NL"
style = "Light"

[font.italic]
family = "JetBrains Mono NL"
style = "ExtraLight"

[font.normal]
family = "JetBrains Mono NL"
style = "ExtraLight"

[window]
startup_mode = "Fullscreen"

[terminal]
shell = { program = "/opt/homebrew/bin/tmux", args = ["new-session", "-A", "-s", "main"] }
